### ISSUE TITLE
Moving to different repo?

### ISSUE THREAD

**Issue by airballking** [code-iai/nav_pcontroller#1]
I'd like to suggest a small contribution to cleaning up our github group: Moving the content of this repo incl. history into https://github.com/code-iai/iai_control_pkgs 

Any thoughts? I'd go ahead and do it on Wednesday if noone objects.

**Comment by gaya-** [comment]
Now that we want to release this package I don't think that would be a good idea. Otherwise the complete `iai_control_pkgs` would have to be released and that's not planned for the nearest future.
