### ISSUE TITLE
Add an install rule for example.launch

### ISSUE THREAD

**Issue by gaya-** [code-iai/nav_pcontroller#5]

**Comment by ghost** [comment]
@gaya- isn't [this](https://github.com/code-iai/nav_pcontroller/blob/master/CMakeLists.txt#L31) the install rule for example.launch?

**Comment by gaya-** [comment]
@gheorghelisca True, I forgot. But the pr2 example shouldn't be installed. Could you please remove it?

**Comment by ghost** [comment]
@gaya- could you please, please leave it there and maybe add the one for boxy too? i want to be able to use this package from debian installation and not from source. in the end i see no harm in having another two examples.

**Comment by gaya-** [comment]
ok
